apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  selector:
    matchLabels:
      app: app-one
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: karthequian/helloworld:latest
        ports:
        - containerPort: 80
