apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: iot-p2
spec:
  selector:
    app: app1
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: iot-p2
spec:
  selector:
    app: app2
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app3-service
  namespace: iot-p2
spec:
  selector:
    app: app3
  ports:
    - name: "http"
      port: 80
      targetPort: 8080