# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "ablevinS"
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"
  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ablevinS"
    vb.memory = 2048
    vb.cpus = 2
    vb.customize ["setproperty", "machinefolder", "#{ENV['HOME']}/sgoinfre"]
  end
  config.vm.provision "shell", path: "scripts/setup.sh"
  config.vm.provision "shell", path: "scripts/run_app.sh"
end
