# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    #Change le default machine folder de la commande "VBoxManage list systemproperties"
    #Pour remettre par defaut a 42 : VBoxManage setproperty machinefolder $HOME/Virtualbox\ Vms
    vb.customize ["setproperty", "machinefolder", "#{ENV['HOME']}/sgoinfre"]
  
  #   # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.define "tchantroS" do |server|
    server.vm.box = "bento/ubuntu-22.04"
    server.vm.hostname = "tchantroS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "tchantroSW" do |serverW|
    serverW.vm.box = "bento/ubuntu-22.04"
    serverW.vm.hostname = "tchantroSW"
    serverW.vm.network "private_network", ip: "192.168.56.111"
    serverW.vm.provision "shell", path: "scripts/agent.sh"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
