Vagrant.configure("2") do |config|

  controller_ip = "192.168.56.110"
  agent_ip = "192.168.56.111"
  k3s_port = "6443"
  k3s_url = "https://#{controller_ip}:#{k3s_port}"
  
  shared_dir = "/vagrant/shared"
  k3s_token = "token"

  # Common script executed on all VMs
  config.vm.provision "shell", path: "scripts/common_setup.sh"

  config.vm.define "ablevinS" do |control|
    control.vm.hostname = "ablevinS"
    control.vm.box = "debian/bookworm64"
    control.vm.box_version = "12.20250126.1"
    control.vm.network "private_network", ip: controller_ip
    control.vm.provider "virtualbox" do |vb|
      vb.name = "ablevinS"
      vb.memory = 1024
      vb.cpus = 1
    end
    control.vm.provision "shell", path: "scripts/install_k3s_controller.sh", env: {"SHARED_DIR" => shared_dir, "K3S_TOKEN" => k3s_token}
  end

  config.vm.define "ablevinSW" do |control|
    control.vm.hostname = "ablevinSW"
    control.vm.box = "debian/bookworm64"
    control.vm.box_version = "12.20250126.1"
    control.vm.network "private_network", ip: agent_ip
    control.vm.provider "virtualbox" do |vb|
      vb.name = "ablevinSW"
      vb.memory = 1024
      vb.cpus = 1
    end
    control.vm.provision "shell", path: "scripts/install_k3s_agent.sh", env: {"K3S_URL" => k3s_url, "SHARED_DIR" => shared_dir, "K3S_TOKEN" => k3s_token}
  end

end
